# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: notify-push 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "notify-push"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Erik Nomitch"]
  s.date = "2015-06-08"
  s.description = "A general purpose popup notifier sender/receiver using WebSockets (via Pusher)"
  s.email = "erik@nomitch.com"
  s.executables = ["notify-push"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/notify-push",
    "contrib/irssi/notify_push.pl",
    "contrib/shell/notify-push-curl",
    "images/doc/terminal-notifier.png",
    "lib/notify-push.rb",
    "notify-push.gemspec",
    "ofe.json",
    "system/com.notify-push.receiver.plist",
    "test/helper.rb",
    "test/test_notify-push.rb"
  ]
  s.homepage = "http://github.com/eriknomitch/notify-push"
  s.licenses = ["GPL-2"]
  s.post_install_message = "---------------------------------------------------------------\nIf you have not done so, you will need to create a configuration file at:\n\n~/.notify-pushrc\n\nSee the instructions/example at:\n\nhttps://github.com/eriknomitch/notify-push#create--distribute-configuration-file\n\nOr, modify this example.  It's pretty straightforward:\n\npusher:\n  key: a1a2a3b1b2b3c1c2c3d1\n  secret: a1a2a3b1b2b3c1c3c1d1\n  app_id: 12345\n\n---------------------------------------------------------------\n"
  s.rubygems_version = "2.4.6"
  s.summary = "A general purpose popup notifier sender/receiver using WebSockets (via Pusher)"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pusher>, [">= 0"])
      s.add_runtime_dependency(%q<pusher-client>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<recursive-open-struct>, [">= 0"])
      s.add_runtime_dependency(%q<pidfile>, [">= 0"])
      s.add_runtime_dependency(%q<os>, [">= 0"])
      s.add_runtime_dependency(%q<notifier>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<pusher>, [">= 0"])
      s.add_dependency(%q<pusher-client>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<recursive-open-struct>, [">= 0"])
      s.add_dependency(%q<pidfile>, [">= 0"])
      s.add_dependency(%q<os>, [">= 0"])
      s.add_dependency(%q<notifier>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<pusher>, [">= 0"])
    s.add_dependency(%q<pusher-client>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<recursive-open-struct>, [">= 0"])
    s.add_dependency(%q<pidfile>, [">= 0"])
    s.add_dependency(%q<os>, [">= 0"])
    s.add_dependency(%q<notifier>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

